
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Default values are provided in case environment variables are missing
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://nfkvvtfgqmihghegarrs.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ma3Z2dGZncW1paGdoZWdhcnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTQxODcsImV4cCI6MjA1ODg5MDE4N30.A6RpJdzhd2OjVIVzTLULJR8jdd5ttJ_aYO7IGm9IM6U';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
